// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/object-assign/object-assign.d.ts
declare module "object-assign" {
  function objectAssign(target: any, ...sources: any[]): any;
  export = objectAssign;
}