
// Dashboard
export const DASHBOARD_IMPORT = "DASHBOARD_IMPORT";

// Layouts
export const ADD_LAYOUT = "ADD_LAYOUT";
export const UPDATE_LAYOUT = "UPDATE_LAYOUT";
export const DELETE_LAYOUT = "DELETE_LAYOUT";
export const LOAD_LAYOUT = "LOAD_LAYOUT";
export const SET_CURRENT_LAYOUT = "SET_CURRENT_LAYOUT";

// Widgets
export const ADD_WIDGET = "ADD_WIDGET";
export const UPDATE_WIDGET_PROPS = "UPDATE_WIDGET_PROPS";
export const DELETE_WIDGET = "DELETE_WIDGET";
export const UPDATE_WIDGET_LAYOUT = "UPDATE_WIDGET_LAYOUT";

export const START_CREATE_WIDGET = "START_CREATE_WIDGET";
export const START_CONFIGURE_WIDGET = "START_CONFIGURE_WIDGET";

// Datasources
export const ADD_DATASOURCE = "ADD_DATASOURCE";
export const UPDATE_DATASOURCE = "UPDATE_DATASOURCE";
export const DELETE_DATASOURCE = "DELETE_DATASOURCE";